M48
; DRILL file {KiCad 9.0.4} date 2025-11-06T14:53:44-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-06T14:53:44-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.286
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.302
%
G90
G05
T1
X90.305Y-46.645
X160.155Y-46.645
T2
X120.344Y-165.995
X130.505Y-165.995
M30
